# Generated by Django 5.2.1 on 2025-05-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("profession", models.CharField(max_length=100)),
                ("short_bio", models.TextField()),
                ("hobbies", models.TextField()),
            ],
        ),
    ]
